version: '3.8'

services:
  spring-app:
    image: your-dockerhub-username/your-spring-app:latest  # Replace with your actual Docker Hub repo
    container_name: spring_app_container
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/your_database
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: changemeinprod!
    depends_on:
      - db
    networks:
      - app_network

  db:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: your_database
      POSTGRES_USER: your_db_user
      POSTGRES_PASSWORD: your_db_password
    ports:
      - "5432:5432"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
